server:
    port: 8080
spring:
    datasource:
        url: jdbc:h2:tcp://localhost/~/test
        driver-class-name: org.h2.Driver
        username: sa
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        # table 없을 시 자동 생성
        properties.hibernate.hbm2ddl.auto: update
        #properties.hibernate.hbm2ddl.auto: none
        showSql: true
    messages:
        basename: i18n/exception
        encoding: UTF-8
    jwt:
        secret: govlepel@$&